services:
  app:
    build: .
    container_name: pour
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blogdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
    # Wait for the database to be ready
    restart: on-failure

  db:
    image: postgres:15-alpine
    container_name: pour-db-postgres
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d blogdb"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  pgdata: 
