spring:
  datasource:
    url: jdbc:postgresql://db:5432/blogdb
    # For local testing (without Docker)
    # url: jdbc:postgresql://localhost:5432/blogdb
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true